### ISSUE TITLE
Implement configuration through yml file

### ISSUE THREAD

**Issue by nikmel2803** [codex-team/workflow#4]
Now there is a problem with the fact that the names in the Telegram and GitHub can be different.
We need to set the correspondence of names in the configuration.
The .env files are not very convenient for this, so we can use .yml files as following:

```yml
token: wedwedwedw
columnId: erferferf
notifierUrl: https://kek.so/
prTime: 0 9,18 * * 1-5
mention:
  - guryn
  - tg: specc
    gh: neSpecc
```

JSON representation for this config is:
```json

{
  "mention": [
    "guryn", 
    {
      "tg": "specc", 
      "gh": "neSpecc"
    }
  ], 
  "notifierUrl": "https://kek.so/", 
  "prTime": "0 9,18 * * 1-5", 
  "token": "wedwedwedw", 
  "columnId": "erferferf"
}

```
